### ISSUE TITLE
Readme doesn't give a concrete example use case

### ISSUE THREAD

**Issue by AttwellBrian** [uber/artist#4]
When reading Artist's readme it is hard to answer the question "what kind of problems will this solve for me?" Maybe mention a concrete example use case? For example: "this can be used for adding automatic analytics to every view".

Close this issue if you disagree.

**Comment by hzsweers** [comment]
@attwell see #1

**Comment by hzsweers** [comment]
Oops I mean #2. Counting is hard

**Comment by jbarr21** [comment]
319f7aa
